name: ci

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - name: Xcodebuild test
      run: xcodebuild clean test -project TODOs.xcodeproj -scheme TODOs -destination "platform=iOS Simulator,name=iPhone X"
